export const routes = {
  masterMerchant: '/master-merchants',
  masterMerchantDetail: '/master-merchants/:id',
  editMasterMerchant: '/master-merchants/:id/edit',
  merchant: '/merchants',
  createMerchant: '/merchants/create-merchant',
  merchantDetail: '/merchants/:id',
  editMerchant: '/merchants/:id/edit',
  staff: '/staffs',
  staffDetail: '/staffs/:id',
  createStaff: '/staffs/create',
  editStaff: '/staffs/:id/edit',
  transaction: '/transactions',
  transactionDetail: '/transactions/:transactionId',
} as any;
