export const routes = {
  masterMerchant: '/master-merchants',
  masterMerchantDetail: '/master-merchants/:merchantId',
  editMasterMerchant: '/merchants/:merchantId/edit',
  merchant: '/merchants',
  createMerchant: '/merchants/create-merchant',
  merchantDetail: '/merchants/:merchantId',
  editMerchant: '/merchants/:merchantId/edit',
  staff: '/staffs',
  staffDetail: '/staffs/:staffId',
  createStaff: '/staffs/create',
  editStaff: '/staffs/:staffId/edit',
  transaction: '/transactions',
  transactionDetail: '/transactions/:transactionId',
}
